### ISSUE TITLE
UnicodeDecodeErrors when loading message catalogs in Python 3.6

### ISSUE THREAD

**Issue by davisagli** [zopefoundation/zope.app.locales#5]
I am getting UnicodeDecodeErrors in Python 3.6 when trying to load the Polish and Turkish message catalogs included in the 4.0.0 release of zope.app.locales:

```
>>> gettext.GNUTranslations(open('pl/LC_MESSAGES/zope.mo', 'rb'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/gettext.py", line 254, in __init__
    self._parse(fp)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/gettext.py", line 413, in _parse
    catalog[str(msg, charset)] = str(tmsg, charset)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 15: ordinal not in range(128)
>>> gettext.GNUTranslations(open('tr/LC_MESSAGES/zope.mo', 'rb'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/gettext.py", line 254, in __init__
    self._parse(fp)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/gettext.py", line 413, in _parse
    catalog[str(msg, charset)] = str(tmsg, charset)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 9: ordinal not in range(128)
```

The other message catalogs load successfully.

**Comment by ale-rt** [comment]
I also had this randomly.
What I noted running in a checkout of zope.app.locales:
```
msgunfmt pl/LC_MESSAGES/zope.mo > pl/LC_MESSAGES/zope.po
```
is that the mo file appears to be outdated.
```
[ale@emily locales]$ git diff|grep POT
-"POT-Creation-Date: Mon May 22 13:53:11 2006\n"
+"POT-Creation-Date: Mon Dec  5 17:28:09 2005\n"
```

**Comment by pbauer** [comment]
This is also the reason why jenkins fails: https://jenkins.plone.org/view/PLIPs/job/plip-py3/28/consoleText. 

In https://github.com/plone/buildout.coredev/commit/c9b23f8b76f3e1011ac6858c7139267cf583314d I added a workaround for now. I do not know if that works since github has a problem with https://github.com/plone/collective.monkeypatcher at the moment.

**Comment by icemac** [comment]
@ale-rt Would you create a PR fixing this issue in the repos, too?
